### ISSUE TITLE
Way forward with Interop-switch

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/design-authority#10]
## **Request**:
Need to discuss the approach for the switch going forward. Once we introduce the ALS, participant capabilities will have been moved from Switch/Central-Directory to the ALS. As such do we need to update the Switch to support the ALS, or do we ignore those capabilities on the switch.
Even if we do this, we still have another issue. Quotes.....this is still done by the switch. Which means we still need to register DFSP routes on the switch to support it going forward.

**Artifacts**:
- [ ] Artifact to consider [@Contributor]

**Decision(s)**:
- [ ] Actual decision made as a result of discussion

## **Follow-up**:
- [ ] Alternative actions

**Dependencies**:
- [ ] If Applicable

## **Accountability**:
- Owner: 

## **Notes**:

**Comment by mdebarros** [comment]
I believe this item can be closed as we have deprecated the Interop-Switch with the introduction of the following recently released components to the OSS community:
- Account Lookup Service
- Quoting Service

Both of the above items have been made available via Github and also incorporated as part of the existing Mojaloop Helm Chart (https://github.com/mojaloop/helm/releases/tag/v6.3.0) deprecating the following components:
- Central-Directory
- Central-End-User-Registry
- Mock-Pathfinder
- Interop-Switch
