### ISSUE TITLE
Software Quality Report

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/design-authority#13]
## **Request**:
It would be necessary to provide proof of the level of software quality that had been applied as part of the software delivery.
code development guidelines are kept, unit test code coverage report

**Artifacts**:
- [ ] Artifact to consider [@Contributor]

**Decision(s)**:
- [ ] Actual decision made as a result of discussion

## **Follow-up**:
- [ ] Alternative actions

**Dependencies**:
- [ ] If Applicable

## **Accountability**:
- Owner: 

## **Notes**:

**Comment by elnyry** [comment]
SonarQube is now setup, up-to-date and running.. In fact quite a few issues reported have been addressed. But this will be finalized over the course of PI-7
