### ISSUE TITLE
Discuss Event Sourcing (CQRS)

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/design-authority#18]
## **Request**:

**Artifacts**:
- [ ] Artifact to consider [@Contributor]

**Decision(s)**:
- [ ] Actual decision made as a result of discussion

## **Follow-up**:
- [ ] Alternative actions

**Dependencies**:
- [ ] If Applicable

## **Accountability**:
- Owner: 

## **Notes**:

**Comment by mdebarros** [comment]
This will be addressed as part of the Performance work in PI8.
