### ISSUE TITLE
TypeScript adoption for all new NodeJS services/components going forward. Example https://github.com/mojaloop/central-services-metrics

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/design-authority#2]
## **Request**:

**Artifacts**:
- [ ] Artifact to consider [@Contributor]

**Decision(s)**:
- [ ] Draft a best practices / guidelines doc or a template. 
- [ ] Mojaloop template project
- [ ] Add related tools (typescript, eslint) to the list in the documentation [here](https://mojaloop.io/documentation/contributors-guide/tools-and-technologies/)

## **Follow-up**:
- [ ] Alternative actions
- [ ] Create a Repository Template for a Typescript Project  https://github.com/mojaloop/project/issues/850

**Dependencies**:
- [ ] If Applicable

## **Accountability**:
- Owner: 

## **Notes**:
- Not mandated to use in all the services, javascript is still used
- typescript preferred where possible

**Comment by mdebarros** [comment]
@NicoDuvenage when can we have this discussion? 

I believe it was supposed to occur in April 2019 during Mojacon, but was deferred at the time?

**Comment by elnyry** [comment]
event-sdk, central-services-health are now in typescript as indicated by @lewisdaly @mdebarros

**Comment by adrianhopebailie** [comment]
We have an advantage of targeting modern versions of Node and Typescript. 

We should require at least Typescript 3.2+ (for BigInt support) and the tsconfig should target **ES2018** which enables a lot of modern ECMAScript features to be used and is fully supported in Node 10 LTS (https://node.green/#ES2018).

Suggest we also use ESM modules (as opposed to CJS). 

Here's a decent starting `tsconfig.json`:
```json
{
  "include": ["src"],
  "compilerOptions": {
    "target": "es2018",
    "module": "esnext",
    "lib": ["dom", "esnext"],
    "importHelpers": true,
    "declaration": true,
    "sourceMap": true,
    "rootDir": "./src",
    "outDir": "./dist",
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "moduleResolution": "node",
    "baseUrl": "./",
    "paths": {
      "*": ["src/*", "node_modules/*"]
    },
    "esModuleInterop": true
  }
}
```

and `package.json`

```json
{
  "name": "mojaloop-widget",
  "version": "0.1.0",
  "main": "dist/index.js",
  "typings": "dist/index.d.ts",
  "files": [
    "dist"
  ],
  "scripts": {
    "build": "tsc",
  },
  "devDependencies": {
    "typescript": "^3.5.2"
  }
}
```

**Comment by adrianhopebailie** [comment]
Also note that Microsoft are moving to eslint (as opposed to tslint) so we should use it from the start: https://javascriptplayground.com/typescript-eslint

**Comment by lewisdaly** [comment]
Thanks @adrianhopebailie, those look like a good starting point.

If we are happy with these default settings, we should also go back to the existing TS projects and update them to comply with the `tsconfig.json` and typescript version above.

**Comment by lewisdaly** [comment]
I've started working on the ticket above. One thing we need to decide is whether or not to include the `dist` folder in git or not.

I would prefer to *not* include it, as from experience it causes unnecessarily large git diffs and makes code conflicts more annoying to resolve.

**Comment by adrianhopebailie** [comment]
+1 to not including `dist` in git and not including `src` and `test` from the distributed packages

**Comment by NicoDuvenage** [comment]
The outcome is that the Switch development will not be restrictive and prescriptive but as far as recommendation for new contributions and modules are concerned, it will be preferred if those could be done in TypeScript
