### ISSUE TITLE
Operation API renaming discussion

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/design-authority#21]
## **Request**:

**Artifacts**:
- [ ] Artifact to consider [@Contributor]

**Decision(s)**:
- [ ] Actual decision made as a result of discussion

## **Follow-up**:
- [ ] Alternative actions

**Dependencies**:
- [ ] If Applicable

## **Accountability**:
- Owner: 

## **Notes**:

**Comment by elnyry** [comment]
Duplicate of #20
