### ISSUE TITLE
Investigate licensing issues highlighted for many of the 3rd party services Mojaloop uses

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/design-authority#23]
## **Request**:
MongoDB "open-source" Server Side Public License rejected | ZDNet
Red Hat won't use MongoDB in Red Hat Enterprise Linux or Fedora thanks to MongoDB's new Server Side Public License.

**Artifacts**:
- [ ] Artifact to consider [@Contributor]

**Decision(s)**:
- [ ] Actual decision made as a result of discussion

## **Follow-up**:
- [ ] Alternative actions

**Dependencies**:
- [ ] If Applicable

## **Accountability**:
- Owner: 

## **Notes**:

**Comment by lewisdaly** [comment]
I've done a little digging around ahead of our next opportunity to discuss this:

## Links:
- [MongoDB FAQ](https://www.mongodb.com/licensing/server-side-public-license/faq)
- [ZDNet Article](https://www.zdnet.com/article/mongodb-open-source-server-side-public-license-rejected/)

## General Summary:
- The license is based on GPLv3, with a chance to the 
- The change is targeted at cloud vendors who resell MongoDB as a service, but don't offer anything back to the community (e.g. AWS)
- The main crux of the point in the license:
> If you make the functionality of the Program or a modified version available to third parties as a service, you must make the Service Source Code available via network download to everyone at no charge, under the terms of this License. 
- Businesses using MongoDB as part their SaaS application are unaffected


## Thoughts:
- It doesn't look like this license change will affect us directly. 
- This will have an effect on cloud service providers: Mojaloop deployments that rely on off-the-shelf MongoDB instances and support contracts with cloud service providers may be adversely affected
- One potential issue would be for vendors offering to host Mojaloop as a Service and exposing a direct interface to MongoDB in a way that could be construed as "offering MongoDB as a service" - which I don't think is a real use case

**Comment by lewisdaly** [comment]
We have handed this off to Paula to discuss with the Foundation for now.

**Comment by lewisdaly** [comment]
I think this is worth closing for now, since I don't think directly affects us at the moment. Feel free to re-open if this changes in the future.
