### ISSUE TITLE
Discuss the currency issue - data model of Amount to use integers and not Strings

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/design-authority#25]
## **Request**:

**Artifacts**:
- [ ] Artifact to consider [@Contributor]

**Decision(s)**:
- [ ] Actual decision made as a result of discussion

## **Follow-up**:
- [ ] Alternative actions

**Dependencies**:
- [ ] If Applicable

## **Accountability**:
- Owner: 

## **Notes**:

**Comment by adrianhopebailie** [comment]
@elnyry please can you provide some links to the related context for this issue

**Comment by elnyry** [comment]
Thanks Adrian. here's the issue that started the conversation - https://github.com/mojaloop/project/issues/867, though the core issue itself was on the backlog / pipeline for a while.

Here's the first step of this being addressed, this is now merged - https://github.com/mojaloop/project/issues/949

Here's another follow-up item: https://github.com/mojaloop/project/issues/952
