### ISSUE TITLE
Discuss Header and Body parsing (HAPI results?) which influences JWS and security as a whole

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/design-authority#26]
## **Request**:

**Artifacts**:
- [ ] Artifact to consider [@Contributor]

**Decision(s)**:
- [ ] Actual decision made as a result of discussion

## **Follow-up**:
- [ ] Alternative actions

**Dependencies**:
- [ ] If Applicable

## **Accountability**:
- Owner: 

## **Notes**:

**Comment by mdebarros** [comment]
The issue was resolved, discussed and documented by the following issue: https://github.com/mojaloop/project/issues/755. And seems to be
