### ISSUE TITLE
Answer the question of how to manage notifications so that a PISP can be registered as an interested party for notification of the success of a transfer

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/design-authority#48]
## **Request**:
Answer the question of how to manage notifications so that a PISP can be registered as an interested party for notification of the success of a transfer

**Artifacts**:
- [ ] Artifact to consider [@Contributor]

**Decision(s)**:
- [ ] Actual decision made as a result of discussion

## **Follow-up**:
- [ ] Alternative actions

**Dependencies**:
- [ ] If Applicable

## **Accountability**:
- Owner:

**Comment by lewisdaly** [comment]
@NicoDuvenage @MichaelJBRichards is this a duplicate of #43 ?

**Comment by NicoDuvenage** [comment]
@lewisdaly : Correct...I labeled it as such and closed #48
