### ISSUE TITLE
Final Review ALS Design (Sequence Diagrams)

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/design-authority#5]
## **Request**:

**Artifacts**:
- [x]  https://github.com/mojaloop/documentation/tree/master/mojaloop-technical-overview/account-lookup-service [ ]

**Decision(s)**:
- [x] The design has been documented and published in the following Mojaloop documentation location: https://github.com/mojaloop/documentation/tree/master/mojaloop-technical-overview/account-lookup-service

This was reviewed and approved prior to the April 2019 convening, and as such, I believe this issue can be closed.

## **Follow-up**:
- [ ] Alternative actions

**Dependencies**:
- [ ] If Applicable

## **Accountability**:
- Owner: 

## **Notes**:

**Comment by mdebarros** [comment]
The design has been documented and published in the following Mojaloop documentation location: https://github.com/mojaloop/documentation/tree/master/mojaloop-technical-overview/account-lookup-service

This was reviewed and approved prior to the April 2019 convening, and as such, I believe this issue can be closed.
