### ISSUE TITLE
Placement of Rules modules

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/design-authority#53]
## **Request**:
Discuss the approach to be implemented when deploying Rules Engine rules, database and modules.

**Artifacts**:
- [ ] Artifact to consider [@Contributor]

**Decision(s)**:
- [ ] Actual decision made as a result of discussion

## **Follow-up**:
- [ ] Alternative actions

**Dependencies**:
- [ ] If Applicable

## **Accountability**:
- Owner:

**Comment by NicoDuvenage** [comment]
@ndonnan will revert back with a demonstration of how TIPS implemented their Rules-Based solution and a determination will be made if that design approach is generic enough as well as if the design is sound enough for integration into the core codebase of Mojaloop OSS.

**Comment by godfreykutumela** [comment]
Hi @ndonnan, can you please advise on the status of this issue? If it is not open for further discussion, I suggest moving it to closed or deferred.

**Comment by ndonnan** [comment]
This can be closed

**Comment by godfreykutumela** [comment]
Thanks, @ndonnan and I will close it
