### ISSUE TITLE
central-settlement merge into central-ledger

### ISSUE THREAD

**Issue by ndonnan** [mojaloop/design-authority#58]
## **Request**:
Currently the central-settlement module is dependant on the central-ledger tables and is tightly integrated with central-ledger functionality. I would like to discuss the possible merging of the central-settlement repo into the central-ledger to aid in the development and maintenance of settlements development.

**Artifacts**:
- [ ] Artifact to consider [@Contributor]

**Decision(s)**:
- [ ] Actual decision made as a result of discussion

## **Follow-up**:
- [ ] Alternative actions

**Dependencies**:
- [ ] If Applicable

## **Accountability**:
- Owner:

**Comment by claudio-viola** [comment]
I second such a change, currently the database is centralised and at this stage we are unable to properly conduct PR review processes unless a change is committed and merged into central-ledger first hand.
a quick example is a needed change in a central-settlement api which requires a new database attribute.
 in order for such a change to be completed a pull request would need to be made into central_ledger and merged and released before development and review CI/CD can continue in central-settlement service.

So we have two options, 
1) merge back 
2) invest into separating the database across microservices

**Comment by godfreykutumela** [comment]
Hi, @ndonnan @claudio-viola @elnyry-sam-k, can you please advise on the status of this issue? If it is not open for further discussion, I suggest moving it to closed or deferred.

**Comment by ndonnan** [comment]
This will be addressed as part of the event sourcing design

**Comment by godfreykutumela** [comment]
Thanks @ndonnan
