### ISSUE TITLE
Cryptographic Processing Module

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/design-authority#59]
## **Request**:
There is a new cryptographic processing module high-level design completed recently by the quality code workstream which they would like to have reviewed by the DA

**Artifacts**:
- [ ] Artifact to consider [@godfreykutumela]
https://github.com/mojaloop/project/files/4884145/Mojaloop.Crytographic.Processing.Module.-.7.July.2020.v1.0.docx

**Decision(s)**:
- [ ] Actual decision made as a result of discussion

## **Follow-up**:
- [ ] Alternative actions

**Dependencies**:
- [ ] If Applicable

## **Accountability**:
- Owner:

**Comment by godfreykutumela** [comment]
Thanks @NicoDuvenage
