### ISSUE TITLE
Risk: Current dependencies being used by Mojaloop seem to include some viral licenses on key components (Kafka, Hapi, etc).

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/design-authority#6]
## **Request**:
Link to license report that was executed by @rajiv313 : https://mojaloop.slack.com/files/U87PH4C69/FCSGKAF60/screen_shot_2018-09-13_at_11.15.43.png

**Artifacts**:
- [ ] Artifact to consider [@Contributor]

**Decision(s)**:
- [ ] License scan has been completed, across all node projects, and it doesn't look too serious.

## **Follow-up**:
- [ ] Remove the deprecated projects from the license file, and reevaluate any of the dependencies that have unknown or AGPL licenses
- [ ] Add license scanning CI step to all projects (see https://github.com/mojaloop/project/issues/801)

**Dependencies**:
- [ ] If Applicable

## **Accountability**:
- Owner: 

## **Notes**:

**Comment by lewisdaly** [comment]
As a part of [#711](https://github.com/mojaloop/project/issues/711), I implemented this [license-scanner](https://github.com/mojaloop/license-scanner) tool, which allows us to scan dependencies across projects with Fossa cli or exporting to a single `.xlsx` file locally.

Our license scan results showed only a few minor instances of GPL licenses. See attached xlsx file for the summary.

[license-summary.xlsx](https://github.com/mojaloop/design-authority/files/3320939/license-summary.xlsx)


I'm also working on [#801](https://github.com/mojaloop/project/issues/801), which will introduce the license-scanning step into our CI workflow, and fail CI checks when new disallowed licenses are being introduced into our dependencies.

**Comment by lewisdaly** [comment]
I think we can close this ticket. We have other follow up tickets:
- https://github.com/mojaloop/project/issues/912
- https://github.com/mojaloop/project/issues/986

As far as the DA goes on this topic, I think we have the appropriate measures in place to no longer introduce GPL and other unwanted licenses into the codebase.
