### ISSUE TITLE
Decide on accepting Mojawallet

### ISSUE THREAD

**Issue by DonChangfoot** [mojaloop/design-authority#66]
## **Request**:
Community members have shown interest in the [Mojawallet](https://github.com/mojaloop/mojawallet). As such it has been prepped for contribution and reviewed to make sure it follows the Mojaloop contribution standards. A decision needs to be made to make the repo public.

Things to consider:
Currently, the project does not have github releases / docker images setup as it is for demonstration purposes only.

**Artifacts**:
- [ ] Artifact to consider [@Contributor]

**Decision(s)**:
- DA is happy with the tech stack
- Final approval in slack needed after changes below are made

## **Follow-up**:
- [x] update the messaging: not part of core, not a wallet - demonstrates how to use Mojaloop API at hackathon, point to Fineract for actual wallet.
- [x] rename repo to highlight the above
- [x] publish docker images in CI
- [x] get final DA approval in slack

**Dependencies**:
- [ ] If Applicable

## **Accountability**:
- Owner: @DonChangfoot

**Comment by godfreykutumela** [comment]
Hi, @DonChangfoot, can you please advise on the status of this issue? If it is not open for further discussion, I suggest moving it to closed or deferred.

**Comment by DonChangfoot** [comment]
Hi @godfreykutumela. This is closed. I'll update its status.

**Comment by godfreykutumela** [comment]
Thanks @DonChangfoot
