### ISSUE TITLE
Review design of Account Lookup Services with specific focus on the Bank Account Lookup Service, as presented by TIPS.

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/design-authority#8]
## **Request**:

**Artifacts**:
- [ ] Artifact to consider [@Contributor]

**Decision(s)**:
- [ ] Actual decision made as a result of discussion

## **Follow-up**:
- [ ] Alternative actions

**Dependencies**:
- [ ] If Applicable

## **Accountability**:
- Owner: 

## **Notes**:

**Comment by emmakazi** [comment]
Nico, there is no enough information for me to proceed with this.

**Comment by elnyry** [comment]
@emmakazi lets discuss this in tomorrow's meeting
